### ISSUE TITLE
3.2.0 Breaks electron-vue

### ISSUE THREAD

**Issue by No3x** [parro-it/electron-localshortcut#89]
I just setup a new electron-vue project and run into the issue:
# Install vue-cli and scaffold boilerplate
```
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project
```
# Install dependencies and run your app
```
cd my-project
npm install
npm run dev
```
# Error
The last command builds the app and the error is produced.
```js
...
┗ ----------------------------

┏ Electron -------------------

  App threw an error during load
  C:\Users\blibla\myvueelectron\node_modules\electron-localshortcut\index.js:20
                } catch {
                        ^

  SyntaxError: Unexpected token {
      at createScript (vm.js:80:10)
      at Object.runInThisContext (vm.js:139:10)
      at Module._compile (module.js:606:28)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at eval (webpack:///external_%22electron-localshortcut%22?:1:18)

┗ ----------------------------

```
Catch without parameter doesn't seem to be supported by the other tools yet. Not sure if this is your business but wanted to let you know about it.
# Workaround
Use 3.1.0
```
npm install electron-localshortcut@3.1.0
npm run dev
```

**Comment by ROTGP** [comment]
Thanks for the workaround @No3x - very much appreciated
